BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL DEFAULT 0,
	"tg_username"	TEXT NOT NULL DEFAULT '-',
	"tg_id"	INTEGER NOT NULL DEFAULT 0 UNIQUE,
	"ref"	INTEGER NOT NULL DEFAULT -1,
	"right"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "keys" (
	"id"	INTEGER DEFAULT 0,
	"user_id"	INTEGER NOT NULL DEFAULT 0,
	"key"	TEXT NOT NULL DEFAULT 'BIKE-TH1S-1S-JU5T-T35T',
	"type"	TEXT NOT NULL DEFAULT 'BIKE',
	"time"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "promo" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"desc"	TEXT NOT NULL,
	"link"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "promo_log" (
	"id"	INTEGER,
	"user_id"	INTEGER NOT NULL,
	"promo_id"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
